### ISSUE TITLE
to Create a New profile in Brazilian Portuguese

### ISSUE THREAD

**Issue by EvertonMelo** [LicioJr/mbot#1]
add support on Brazilian Porteguese:

https://github.com/LicioJr/mbot/blob/master/docs/index.html

**Comment by LicioJr** [comment]
To use a Portuguese stemmer for natural language processing, just configure `nlp.stemmer` key in `config/core/brain.{env}.json` as following:

```javascript
    "nlp": {
        "type": "bayes",
        "stemmer": "node_modules/natural/lib/natural/stemmers/porter_stemmer_pt.js"
    }
```
(note "_pt" suffix)
